---
- name: Create test containers for Ansible
  hosts: local
  become: true
  collections:
    - community.docker

  tasks:
    - name: Pull Ubuntu image
      community.docker.docker_image:
        name: ubuntu
        source: pull

    - name: Create nginx-test-1 container
      community.docker.docker_container:
        name: nginx-test-1
        image: nginx-python
        command: bash -c "sleep infinity"
        state: started
        restart_policy: always

    - name: Create nginx-test-2 container
      community.docker.docker_container:
        name: nginx-test-2
        image: nginx-python
        command: bash -c "sleep infinity"
        state: started
        restart_policy: always

    - name: create pgs-test-1 container
      community.docker.docker_container:
        name: pgs-test-1
        image: pgs-python
        command: bash -c "sleep infinity"
        state: started
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ansibledb
        ports:
          - "5432:5432"

