---
- name: Create test containers for Ansible
  hosts: local
  become: true
  collections:
    - community.docker

  tasks:
    - name: Pull Ubuntu image
      community.docker.docker_image:
        name: ubuntu
        source: pull

    - name: Create nginx-test-1 container
      community.docker.docker_container:
        name: nginx-test-1
        image: ubuntu:latest
        command: bash -c "apt-get update && apt-get install -y python3 && sleep infinity"
        state: started
        restart_policy: always

    - name: Create nginx-test-2 container
      community.docker.docker_container:
        name: nginx-test-2
        image: ubuntu:latest
        command: bash -c "apt-get update && apt-get install -y python3 && sleep infinity"
        state: started
        restart_policy: always
