---
- name: Create test containers for Ansible
  hosts: local
  become: true
  collections:
    - community.docker

  tasks:
    - name: Build Nginx Base Container
      community.docker.docker_image:
        name: nginx-python
        build:
          path: ./docerfiles/nginx
        source: build

    - name: Build Nginx Base Container
      community.docker.docker_image:
        name: pgs-python
        build:
          path: ./docerfiles/postgres
        source: build

    - name: Create nginx test containers
      community.docker.docker_container:
        name: "{{ item }}"
        image: nginx-python
        state: started
        restart_policy: always
        recreate: false
      loop:
          - nginx-test-1
          - nginx-test-2

    - name: create pgs-test-1 container
      community.docker.docker_container:
        name: pgs-test-1
        image: pgs-python
        state: started
        restart_policy: always
        recreate: false
        pull: false
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: ansibledb
        ports:
          - "5432:5432"

